blog/config/routes.rb
Rails.application.routes.draw do
  #root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/posts', to: 'posts#index', as: :posts
  get '/posts/new', to: 'posts#new', as: :new_post
  get '/posts/:id', to: 'posts#show', as: :post
  post '/posts', to: 'posts#create'
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#delete'
  get '/categories/:category_handle/posts', to: 'posts#index', as: :category_posts
  root to: 'posts#index'

   resources :posts do
     resources :comments
  end
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  def self.find_by_handle(handle)
    find_by(handle)
  end

  def self.find_by_handle!(handle)
    find_by_handle(handle) || raise(ActiveRecord::RecordNotFound)
  end
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :username, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {maximum: 300}
end

blog/app/models/post.rb
class Post < ApplicationRecord

  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :text, presence: true, length: {minimum: 20}

  scope :ordered, -> { order(id: :desc)}
  scope :by_categories, -> { includes(:category)}

end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
   return self.email.split('@')[0]
  end
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_parameters)
    redirect_to post_path(@post)
  end

  private def comments_parameters
    params.require(:comment).permit(:username, :body)
  end

end

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:show, :index]
  def index

    if params[:category_handle]
      @category = Category.find_by_handle!(handle: params[:category_handle])

      @posts = @category.posts.ordered.by_categories
    end
    @posts ||= Post.ordered.by_categories
  end

  def show
    @post = Post.find(params[ :id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
      redirect_to :post
    else
      render 'edit'
    end
  end

  def delete
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :posts
  end

  private def post_params
    params.require(:post).permit(:title, :text, :category_id)
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/pages_helper.rb
module PagesHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/posts/_form.html.erb
<div class="container">
  <%= simple_form_for @post do |f|%>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title , class: "form-control"%>
  </div>
  <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text, class: "form-control", style: "min-height: 150px"%>
  </div>
  <div class="form-group">
      <%= f.association :category, collection: Category.order(:name), prompt: "Choose a Category"%>
  </div>
  <%= f.submit%>
  <% end %>
</div>

blog/app/views/posts/edit.html.erb
<div class="container">
    <h1 style="text-align: center">Edit post "<%= @post.title %>"</h1>
    <%= render partial: 'form' %>
</div>

blog/app/views/posts/index.html.erb
  <br>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h1 class="my-0 mr-md-auto font-weight-normal">Bomjo Blogs</h1>

      <h5 class="my-0 mr-md-auto font-weight-normal">
      <% if current_user %>
         Authorised as: <%= current_user.username %>
      <% else %>
         Not authorised
      <% end %>
       </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark"><%= link_to 'New post', new_post_path %></a>
        <% if current_user %>
          <span class="p-2 text-dark"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></span>
        <% else %>
          <span class="p-2 text-dark"><%= link_to 'Sign up', new_user_registration_path %></span>
          <span class="p-2 text-dark"><%= link_to 'Log in', new_user_session_path %></span>
        <% end %>
      </nav>
    </div>

<div class="container">
  <h3 style="text-align: center">
      <%= @category&.name || "All" %> posts
  </h3><hr>
  <% if @category%>
    <div class="link-container">
    <%= link_to "Go back to all posts", posts_path %>
    </div>
    <hr>
  <% end %>
  <div class="posts-container">
   <% @posts.each do  |post| %>
    <div class="post">
      <%= link_to post do  %>
       <h3> <%= post.title %></h3>
       <% end %>
       Category: <%= link_to post.category.name, category_posts_path(category_handle: post.category.handle) %>
       <p> Created at: <%= post.created_at %> </p>
       <hr>
    </div>
   <% end %>
  </div>
</div>

blog/app/views/posts/new.html.erb
<div class="container">
  <h1 style="text-align: center">New post</h1><hr>
  <%= render partial: 'form' %>
  <hr>
</div>

blog/app/views/posts/show.html.erb
<div class="container">
  <br>
    <h3 style="text-align: center"> <%= @post.title %></h3><hr>
    <div class="post">
       <p> Category: <%= @post.category.name %> </p>
       <p> <%= @post.text %> </p>
       <p> Created by: <%= @post.user.username %> </p>
       <p> Created at: <%= @post.created_at %> </p>
    </div>

    <% if current_user && current_user.admin %>
    <hr>
    <div class="link-container" style="text-align: center">
      <%= link_to 'Edit', edit_post_path(@post.id), :class => 'btn btn-warning' %>
        <%= link_to 'Delete', post_path(@post.id), method: :delete,
            data: {confirm: "Your post will be deleted.\nConfirm your action."},
            remote: true, :class => 'btn btn-danger'
        %>
    </div><hr>
    <% end %>
<h1 style="text-align: center">All comments</h1>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong> : <%= comment.body %></p>
  </div>
<% end %>
<hr>
  <h2 style="text-align: center">Add comment</h2>

  <%= form_for([@post, @post.comments.build]) do |f|%>
    <p>
      User <br>
      <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
      Comment text <br>
      <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p style="text-align: center">
      <%= f.submit("Add comment",{:class => 'btn btn-warning'}) %>
    </p>
    <% end %>
    <hr>
    <div class="link-container" style="text-align: center">
      <%= link_to 'Back to all posts', posts_path %>
    </div>
    <br>
</div>